version: '3'
services:
  web:
    image: node:16
    container_name: nexus_erp
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network
    environment:
      - NODE_ENV=development

networks:
  app-network:
    driver: bridge
