name: Deploy Nexus ERP App to Vercel with Docker

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t nexus-erp .

      # Run Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name nexus-erp nexus-erp

      # Copy files from Docker container (output files in the container)
      - name: Copy files from Docker container
        run: |
          docker cp nexus-erp:/app/.next ./out

      # Set up Vercel CLI
      - name: Set up Vercel CLI
        run: |
          curl -sL https://github.com/vercel/vercel/releases/download/v28.0.0/vercel-28.0.0-linux-x64.tar.gz | tar -xz -C /usr/local/bin

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

